# Task 1
A'zra Zulaikha Binti Zainol
P137262

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
import random

In [4]:
a = [round(random.uniform(0.000, 10.000), 3) for _ in range(1)]
A = np.array(a)
print(A)

[6.389]


In [5]:
b = [round(random.uniform(0.000, 10.000), 3) for _ in range(1)]
B = np.array(b)
print(B)

[9.443]


In [6]:
c1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
c2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
c3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
C = np.array([c1, c2, c3])
print(C)

[[4.762 1.137 3.061]
 [2.207 4.505 1.951]
 [3.81  2.468 7.595]]


In [7]:
d1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
d2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
d3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(3)]
D = np.array([d1, d2, d3])
print(D)

[[5.852 8.323 2.827]
 [9.819 0.896 8.055]
 [1.435 4.316 8.974]]


In [8]:
e1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(4)]
e2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(4)]
E = np.array([e1, e2])
print(E)

[[5.395 1.679 4.526 1.083]
 [4.37  5.628 6.351 6.774]]


In [9]:
f1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(4)]
f2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(4)]
F = np.array([f1, f2])
print(F)

[[2.413 3.83  8.671 9.561]
 [6.493 8.247 6.528 6.528]]


In [10]:
g1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
g2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
g3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
g4 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
G = np.array([g1, g2, g3, g4])
print(G)

[[1.93  6.364]
 [0.899 7.013]
 [4.049 9.575]
 [2.544 4.644]]


In [11]:
h1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
h2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
h3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
h4 = [round(random.uniform(0.000, 10.000), 3) for _ in range(2)]
H = np.array([h1, h2, h3, h4])
print(H)

[[6.563 3.543]
 [7.109 3.526]
 [4.515 3.286]
 [3.798 5.007]]


In [12]:
i1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
i2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
i3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
i4 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
i5 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
I = np.array([i1, i2, i3, i4, i5])
print(I)

[[6.984 5.982 6.481 4.684 4.94 ]
 [8.997 6.732 4.269 6.921 9.55 ]
 [5.549 3.673 5.604 1.351 1.994]
 [3.823 2.007 0.75  7.589 5.551]
 [3.563 0.616 8.687 9.705 2.39 ]]


In [13]:
j1 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
j2 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
j3 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
j4 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
j5 = [round(random.uniform(0.000, 10.000), 3) for _ in range(5)]
J = np.array([j1, j2, j3, j4, j5])
print(J)

[[4.882 3.194 0.628 8.073 7.945]
 [9.52  6.156 1.426 5.667 2.318]
 [0.392 2.32  6.545 0.038 3.495]
 [9.81  2.539 0.722 1.744 0.835]
 [8.734 9.848 3.857 4.411 5.238]]


In [14]:
#1 - sqrt

print(np.sqrt(A))
print(np.sqrt(G))
print(np.sqrt(I))

[2.52764713]
[[1.3892444  2.52269697]
 [0.94815611 2.64820694]
 [2.01221271 3.09434969]
 [1.59499216 2.1549942 ]]
[[2.64272587 2.44581275 2.54578082 2.16425507 2.22261108]
 [2.99949996 2.5946098  2.06615585 2.63077935 3.09030743]
 [2.35563155 1.91650724 2.36727692 1.16232526 1.41209065]
 [1.95524934 1.41668627 0.8660254  2.75481397 2.35605603]
 [1.88759106 0.78485667 2.94737171 3.1152849  1.54596248]]


In [15]:
#2 - square

print(np.square(B))
print(np.square(C))
print(np.square(E))

[89.170249]
[[22.676644  1.292769  9.369721]
 [ 4.870849 20.295025  3.806401]
 [14.5161    6.091024 57.684025]]
[[29.106025  2.819041 20.484676  1.172889]
 [19.0969   31.674384 40.335201 45.887076]]


In [16]:
#3 - log

print(np.log(A))
print(np.log(D))
print(np.log(F))

[1.85457776]
[[ 1.76678348  2.11902277  1.03921608]
 [ 2.28431928 -0.10981487  2.08629302]
 [ 0.36116485  1.46232905  2.19433151]]
[[0.88087079 1.3428648  2.15998412 2.25769232]
 [1.87072467 2.1098495  1.87610062 1.87610062]]


In [17]:
#4 - floor

print(np.floor(B))
print(np.floor(H))
print(np.floor(J))

[9.]
[[6. 3.]
 [7. 3.]
 [4. 3.]
 [3. 5.]]
[[4. 3. 0. 8. 7.]
 [9. 6. 1. 5. 2.]
 [0. 2. 6. 0. 3.]
 [9. 2. 0. 1. 0.]
 [8. 9. 3. 4. 5.]]


In [18]:
#5 - rint

print(np.rint(A))
print(np.rint(C))
print(np.rint(E))

[6.]
[[5. 1. 3.]
 [2. 5. 2.]
 [4. 2. 8.]]
[[5. 2. 5. 1.]
 [4. 6. 6. 7.]]


In [19]:
#6 - add(x,y)

print(np.add(C, D))
print(np.add(E, F))
print(np.add(G, H))
print(np.add(I, J))

[[10.614  9.46   5.888]
 [12.026  5.401 10.006]
 [ 5.245  6.784 16.569]]
[[ 7.808  5.509 13.197 10.644]
 [10.863 13.875 12.879 13.302]]
[[ 8.493  9.907]
 [ 8.008 10.539]
 [ 8.564 12.861]
 [ 6.342  9.651]]
[[11.866  9.176  7.109 12.757 12.885]
 [18.517 12.888  5.695 12.588 11.868]
 [ 5.941  5.993 12.149  1.389  5.489]
 [13.633  4.546  1.472  9.333  6.386]
 [12.297 10.464 12.544 14.116  7.628]]


In [20]:
#7 - multiply(x,y)

print(np.multiply(C, D))
print(np.multiply(E, F))
print(np.multiply(G, H))
print(np.multiply(I, J))

[[27.867224  9.463251  8.653447]
 [21.670533  4.03648  15.715305]
 [ 5.46735  10.651888 68.15753 ]]
[[13.018135  6.43057  39.244946 10.354563]
 [28.37441  46.414116 41.459328 44.220672]]
[[12.66659  22.547652]
 [ 6.390991 24.727838]
 [18.281235 31.46345 ]
 [ 9.662112 23.252508]]
[[3.4095888e+01 1.9106508e+01 4.0700680e+00 3.7813932e+01 3.9248300e+01]
 [8.5651440e+01 4.1442192e+01 6.0875940e+00 3.9221307e+01 2.2136900e+01]
 [2.1752080e+00 8.5213600e+00 3.6678180e+01 5.1338000e-02 6.9690300e+00]
 [3.7503630e+01 5.0957730e+00 5.4150000e-01 1.3235216e+01 4.6350850e+00]
 [3.1119242e+01 6.0663680e+00 3.3505759e+01 4.2808755e+01 1.2518820e+01]]


In [21]:
#8 - power(x,y)

print(np.power(C, D))
print(np.power(E, F))
print(np.power(G, H))
print(np.power(I, J))

[[9.25600364e+03 2.91134952e+00 2.36339130e+01]
 [2.37571921e+03 3.85221517e+00 2.17782162e+02]
 [6.81753443e+00 4.93584702e+01 7.97730655e+07]]
[[5.83842044e+01 7.27686246e+00 4.84954351e+05 2.14329857e+00]
 [1.44094024e+04 1.54230466e+06 1.74161963e+05 2.65312319e+05]]
[[7.48363537e+01 7.04070253e+02]
 [4.69113195e-01 9.60852968e+02]
 [5.52300215e+02 1.67502788e+03]
 [3.46859802e+01 2.18337986e+03]]
[[1.32104270e+04 3.02863843e+02 3.23378535e+00 2.59352312e+05
  3.24833349e+05]
 [1.21062684e+09 1.25330024e+05 7.92218713e+00 5.77081124e+04
  1.86916575e+02]
 [1.95763703e+00 2.04573113e+01 7.92355795e+04 1.01149771e+00
  1.11567940e+01]
 [5.16875758e+05 5.86364648e+00 8.12445490e-01 3.42800826e+01
  4.18359827e+00]
 [6.60023490e+04 8.46819506e-03 4.18042948e+03 2.25754973e+04
  9.59507128e+01]]


In [22]:
#9 - maximum(x,y)

print(np.maximum(C, D))
print(np.maximum(E, F))
print(np.maximum(G, H))
print(np.maximum(I, J))

[[5.852 8.323 3.061]
 [9.819 4.505 8.055]
 [3.81  4.316 8.974]]
[[5.395 3.83  8.671 9.561]
 [6.493 8.247 6.528 6.774]]
[[6.563 6.364]
 [7.109 7.013]
 [4.515 9.575]
 [3.798 5.007]]
[[6.984 5.982 6.481 8.073 7.945]
 [9.52  6.732 4.269 6.921 9.55 ]
 [5.549 3.673 6.545 1.351 3.495]
 [9.81  2.539 0.75  7.589 5.551]
 [8.734 9.848 8.687 9.705 5.238]]


In [23]:
#10 - greater_equal(x,y)

print(np.greater_equal(C, D))
print(np.greater_equal(E, F))
print(np.greater_equal(G, H))
print(np.greater_equal(I, J))

[[False False  True]
 [False  True False]
 [ True False False]]
[[ True False False False]
 [False False False  True]]
[[False  True]
 [False  True]
 [False  True]
 [False False]]
[[ True  True  True False False]
 [False  True  True  True  True]
 [ True  True False  True False]
 [False False  True  True  True]
 [False False  True  True False]]


In [24]:
#11 - sum

print(np.sum(D))
print(np.sum(H))
print(np.sum(J))

50.497
37.347
110.33699999999999


In [25]:
#12 - mean

print(np.mean(F))
print(np.mean(G))
print(np.mean(I))

6.533875
4.62725
5.13568


In [26]:
#13 - min

print(np.mean(C))
print(np.mean(E))
print(np.mean(H))

3.499555555555555
4.47575
4.668375


In [27]:
#14 - argmin

print(np.argmin(G))
print(np.argmin(D))
print(np.argmin(F))

2
4
0


In [28]:
#15 - cumsum

print(np.sum(C))
print(np.sum(E))
print(np.sum(I))

31.495999999999995
35.806
128.392


In [29]:
#16 - diag

print(np.diag(A))
print(np.diag(D))
print(np.diag(G))

[[6.389]]
[5.852 0.896 8.974]
[1.93  7.013]


In [30]:
#17 - dot(x,y)

print(np.dot(C, D))
print(np.dot(E, H))
print(np.dot(G, F))
print(np.dot(J, I))

[[43.423962 53.864154 50.090123]
 [59.949644 30.825857 60.035238]
 [57.428237 66.701978 98.80814 ]]
[[ 71.89152   45.329656]
 [123.092179  90.114042]]
[[ 45.978542  59.875808  58.279222  59.996922]
 [ 47.704696  61.279381  53.576093  54.376203]
 [ 71.940712  94.472695  97.614479 101.218089]
 [ 36.292164  48.042588  52.375056  54.639216]]
[[125.488192  74.109407 123.867705 184.193612 119.673785]
 [159.710061 116.430087 120.357104 154.626935 145.659581]
 [ 72.526932  44.232155  79.512377  60.9425    45.707198]
 [105.005218  82.442442  87.025334  85.836772  85.825112]
 [206.529452 144.78977  169.07155  198.58874  181.889499]]


In [31]:
#18 - trace

print(np.trace(J))
print(np.trace(G))
print(np.trace(E))

24.564999999999998
8.943
11.023


In [32]:
#19 - eig

print(np.linalg.eig(C))
print(np.linalg.eig(I))
print(np.linalg.eig(D))

(array([11.02293055,  2.72331531,  3.11575415]), array([[-0.46045226, -0.73367809,  0.49709366],
       [-0.39401136,  0.62998043, -0.86599445],
       [-0.79544878,  0.25463918,  0.05432777]]))
(array([ 2.49494829e+01+0.j        ,  6.05169770e+00+0.j        ,
       -4.88832270e-03+1.90444463j, -4.88832270e-03-1.90444463j,
       -1.69240393e+00+0.j        ]), array([[-0.51041138+0.j        ,  0.32582719+0.j        ,
        -0.1769796 +0.1977528j , -0.1769796 -0.1977528j ,
        -0.37946919+0.j        ],
       [-0.63637822+0.j        , -0.12093065+0.j        ,
        -0.42313717-0.4163816j , -0.42313717+0.4163816j ,
         0.72155627+0.j        ],
       [-0.32622968+0.j        ,  0.62320242+0.j        ,
         0.2304456 +0.17337155j,  0.2304456 -0.17337155j,
         0.00619841+0.j        ],
       [-0.31487495+0.j        , -0.69689657+0.j        ,
        -0.27316612-0.07513799j, -0.27316612+0.07513799j,
         0.29705915+0.j        ],
       [-0.35906955+0.j        , -0.

In [33]:
#20 - inv

print(np.linalg.inv(C))
print(np.linalg.inv(I))
print(np.linalg.inv(J))

[[ 0.31433675 -0.01155724 -0.12371779]
 [-0.09974018  0.26199691 -0.02710353]
 [-0.12527508 -0.07933842  0.20253539]]
[[-3.88549381e-01 -1.79763441e-01  7.40338722e-01  4.48568075e-01
  -1.38101253e-01]
 [ 7.69809511e-01 -3.50511950e-01 -3.80176052e-01  1.26743476e-01
  -1.67762281e-01]
 [-6.32121120e-02  2.58440837e-01 -1.81493456e-01 -4.03780030e-01
   1.87212860e-01]
 [ 2.27503940e-01 -2.95763067e-01  6.94572093e-04  3.29045629e-01
  -5.32424436e-02]
 [-3.13223153e-01  6.19965484e-01 -3.48847525e-01 -5.69904911e-01
   2.03261980e-01]]
[[ 5.77601640e-03 -4.54884721e-02  1.90563607e-04  1.55219327e-01
  -1.35017812e-02]
 [-6.55768476e-02 -9.54266544e-03 -8.38592954e-02 -1.12912972e-01
   1.77643857e-01]
 [-4.81660799e-02  1.88914860e-01  2.02999131e-01 -4.36939666e-02
  -1.39026850e-01]
 [ 1.93031558e-02  3.57323334e-01  5.56418315e-02 -1.84930758e-01
  -1.95053471e-01]
 [ 1.32871977e-01 -3.46224772e-01 -3.89885088e-02  1.41378111e-01
   1.46066299e-01]]
